export interface ChoiceOption {
  id: number;
  name: string;
  unavailable: boolean;
  scale?: number;
  parentId?: number;
}

export interface Scales {
  objectType: ChoiceOption[];
  wear: ChoiceOption[];
  series: ChoiceOption[];
  ao: ChoiceOption[];
  area: ChoiceOption[];
}

const objectType: ChoiceOption[] = [
  { id: 1, name: "отдельная квартира", unavailable: false, scale: 1.0 },
  { id: 2, name: "комната", unavailable: true, scale: 0.8 },
];

const wear: ChoiceOption[] = [
  { id: 1, name: "до 5 лет (новостройка)", unavailable: false, scale: 1.0 },
  { id: 2, name: "6-10 лет", unavailable: false, scale: 0.9 },
  { id: 3, name: "10-20 лет", unavailable: false, scale: 0.8 },
  { id: 4, name: "20-30 лет", unavailable: false, scale: 0.7 },
  { id: 5, name: "более 30 лет", unavailable: false, scale: 0.6 },
];

const series: ChoiceOption[] = [
  { id: 1, name: "типовая", unavailable: false, scale: 55492.6 },
  { id: 2, name: "индивидуальная", unavailable: false, scale: 69492.6 },
];

const ao: ChoiceOption[] = [
  { id: 1, name: "ЦАО", unavailable: true },
  { id: 2, name: "САО", unavailable: true },
  { id: 3, name: "СВАО", unavailable: true },
  { id: 4, name: "ВАО", unavailable: true },
  { id: 5, name: "ЮВАО", unavailable: false },
  { id: 6, name: "ЮАО", unavailable: true },
  { id: 7, name: "ЮЗАО", unavailable: true },
  { id: 8, name: "ЗАО", unavailable: true },
  { id: 9, name: "СЗАО", unavailable: true },
  { id: 10, name: "ЗелАО", unavailable: false },
  { id: 11, name: "ТАО", unavailable: false },
  { id: 12, name: "НАО", unavailable: false },
];

const area: ChoiceOption[] = [
  { id: 1, name: "Арбат", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 2, name: "Басманный", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 3, name: "Замоскворечье", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 4, name: "Красносельский", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 5, name: "Мещанский", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 6, name: "Пресненский", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 7, name: "Таганский", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 8, name: "Тверской", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 9, name: "Хамовники", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 10, name: "Якиманка", unavailable: true, scale: 1.0, parentId: 1 },
  { id: 11, name: "Аэропорт", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 12, name: "Беговой", unavailable: true, scale: 1.0, parentId: 2 },
  {
    id: 13,
    name: "Бескудниковский",
    unavailable: true,
    scale: 1.0,
    parentId: 2,
  },
  { id: 14, name: "Войковский", unavailable: true, scale: 1.0, parentId: 2 },
  {
    id: 15,
    name: "Восточное Дегунино",
    unavailable: true,
    scale: 1.0,
    parentId: 2,
  },
  { id: 16, name: "Головинский", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 17, name: "Дмитровский", unavailable: true, scale: 1.0, parentId: 2 },
  {
    id: 18,
    name: "Западное Дегунино",
    unavailable: true,
    scale: 1.0,
    parentId: 2,
  },
  { id: 19, name: "Коптево", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 20, name: "Левобережный", unavailable: true, scale: 1.0, parentId: 2 },
  {
    id: 21,
    name: "Молжаниновский",
    unavailable: true,
    scale: 1.0,
    parentId: 2,
  },
  { id: 22, name: "Савёловский", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 23, name: "Сокол", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 24, name: "Тимирязевский", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 25, name: "Ховрино", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 26, name: "Хорошёвский", unavailable: true, scale: 1.0, parentId: 2 },
  { id: 27, name: "Алексеевский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 28, name: "Алтуфьевский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 29, name: "Бабушкинский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 30, name: "Бибирево", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 31, name: "Бутырский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 32, name: "Лианозово", unavailable: true, scale: 1.0, parentId: 3 },
  {
    id: 33,
    name: "Лосиноостровский",
    unavailable: true,
    scale: 1.0,
    parentId: 3,
  },
  { id: 34, name: "Марфино", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 35, name: "Марьина Роща", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 36, name: "Останкинский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 37, name: "Отрадное", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 38, name: "Ростокино", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 39, name: "Свиблово", unavailable: true, scale: 1.0, parentId: 3 },
  {
    id: 40,
    name: "Северное Медведково",
    unavailable: true,
    scale: 1.0,
    parentId: 3,
  },
  { id: 41, name: "Северный", unavailable: true, scale: 1.0, parentId: 3 },
  {
    id: 42,
    name: "Южное Медведково",
    unavailable: true,
    scale: 1.0,
    parentId: 3,
  },
  { id: 43, name: "Ярославский", unavailable: true, scale: 1.0, parentId: 3 },
  { id: 44, name: "Богородское", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 45, name: "Вешняки", unavailable: true, scale: 1.0, parentId: 4 },
  {
    id: 46,
    name: "Восточное Измайлово",
    unavailable: true,
    scale: 1.0,
    parentId: 4,
  },
  { id: 47, name: "Восточный", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 48, name: "Гольяново", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 49, name: "Ивановское", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 50, name: "Измайлово", unavailable: true, scale: 1.0, parentId: 4 },
  {
    id: 51,
    name: "Косино-Ухтомский",
    unavailable: true,
    scale: 1.0,
    parentId: 4,
  },
  { id: 52, name: "Метрогородок", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 53, name: "Новогиреево", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 54, name: "Новокосино", unavailable: true, scale: 1.0, parentId: 4 },
  { id: 55, name: "Перово", unavailable: true, scale: 1.0, parentId: 4 },
  {
    id: 56,
    name: "Преображенское",
    unavailable: true,
    scale: 1.0,
    parentId: 4,
  },
  {
    id: 57,
    name: "Северное Измайлово",
    unavailable: true,
    scale: 1.0,
    parentId: 4,
  },
  {
    id: 58,
    name: "Соколиная Гора",
    unavailable: true,
    scale: 1.0,
    parentId: 4,
  },
  { id: 59, name: "Сокольники", unavailable: true, scale: 1.0, parentId: 4 },
  {
    id: 60,
    name: "Выхино-Жулебино",
    unavailable: false,
    scale: 1.0,
    parentId: 5,
  },
  { id: 61, name: "Капотня", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 62, name: "Кузьминки", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 63, name: "Лефортово", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 64, name: "Люблино", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 65, name: "Марьино", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 66, name: "Некрасовка", unavailable: false, scale: 1.0, parentId: 5 },
  {
    id: 67,
    name: "Нижегородский",
    unavailable: false,
    scale: 1.0,
    parentId: 5,
  },
  { id: 68, name: "Печатники", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 69, name: "Рязанский", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 70, name: "Текстильщики", unavailable: false, scale: 1.0, parentId: 5 },
  { id: 71, name: "Южнопортовый", unavailable: false, scale: 1.0, parentId: 5 },
  {
    id: 72,
    name: "Бирюлёво Восточное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 73,
    name: "Бирюлёво Западное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  { id: 74, name: "Братеево", unavailable: true, scale: 1.0, parentId: 6 },
  { id: 75, name: "Даниловский", unavailable: true, scale: 1.0, parentId: 6 },
  { id: 76, name: "Донской", unavailable: true, scale: 1.0, parentId: 6 },
  { id: 77, name: "Зябликово", unavailable: true, scale: 1.0, parentId: 6 },
  {
    id: 78,
    name: "Москворечье-Сабурово",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 79,
    name: "Нагатино-Садовники",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 80,
    name: "Нагатинский Затон",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  { id: 81, name: "Нагорный", unavailable: true, scale: 1.0, parentId: 6 },
  {
    id: 82,
    name: "Орехово-Борисово Северное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 83,
    name: "Орехово-Борисово Южное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  { id: 84, name: "Царицыно", unavailable: true, scale: 1.0, parentId: 6 },
  {
    id: 85,
    name: "Чертаново Северное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 86,
    name: "Чертаново Центральное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  {
    id: 87,
    name: "Чертаново Южное",
    unavailable: true,
    scale: 1.0,
    parentId: 6,
  },
  { id: 88, name: "Академический", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 89, name: "Гагаринский", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 90, name: "Зюзино", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 91, name: "Коньково", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 92, name: "Котловка", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 93, name: "Ломоносовский", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 94, name: "Обручевский", unavailable: true, scale: 1.0, parentId: 7 },
  {
    id: 95,
    name: "Северное Бутово",
    unavailable: true,
    scale: 1.0,
    parentId: 7,
  },
  { id: 96, name: "Тёплый Стан", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 97, name: "Черёмушки", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 98, name: "Южное Бутово", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 99, name: "Ясенево", unavailable: true, scale: 1.0, parentId: 7 },
  { id: 100, name: "Внуково", unavailable: true, scale: 1.0, parentId: 8 },
  { id: 101, name: "Дорогомилово", unavailable: true, scale: 1.0, parentId: 8 },
  { id: 102, name: "Крылатское", unavailable: true, scale: 1.0, parentId: 8 },
  { id: 103, name: "Кунцево", unavailable: true, scale: 1.0, parentId: 8 },
  { id: 104, name: "Можайский", unavailable: true, scale: 1.0, parentId: 8 },
  {
    id: 105,
    name: "Ново-Переделкино",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  {
    id: 106,
    name: "Очаково-Матвеевское",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  {
    id: 107,
    name: "Проспект Вернадского",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  { id: 108, name: "Раменки", unavailable: true, scale: 1.0, parentId: 8 },
  { id: 109, name: "Солнцево", unavailable: true, scale: 1.0, parentId: 8 },
  {
    id: 110,
    name: "Тропарёво-Никулино",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  {
    id: 111,
    name: "Филёвский Парк",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  {
    id: 112,
    name: "Фили-Давыдково",
    unavailable: true,
    scale: 1.0,
    parentId: 8,
  },
  { id: 113, name: "Куркино", unavailable: true, scale: 1.0, parentId: 9 },
  { id: 114, name: "Митино", unavailable: true, scale: 1.0, parentId: 9 },
  {
    id: 115,
    name: "Покровское-Стрешнево",
    unavailable: true,
    scale: 1.0,
    parentId: 9,
  },
  {
    id: 116,
    name: "Северное Тушино",
    unavailable: true,
    scale: 1.0,
    parentId: 9,
  },
  { id: 117, name: "Строгино", unavailable: true, scale: 1.0, parentId: 9 },
  {
    id: 118,
    name: "Хорошёво-Мнёвники",
    unavailable: true,
    scale: 1.0,
    parentId: 9,
  },
  { id: 119, name: "Щукино", unavailable: true, scale: 1.0, parentId: 9 },
  { id: 120, name: "Южное Тушино", unavailable: true, scale: 1.0, parentId: 9 },
  { id: 121, name: "Крюково", unavailable: false, scale: 1.0, parentId: 10 },
  { id: 122, name: "Матушкино", unavailable: false, scale: 1.0, parentId: 10 },
  { id: 123, name: "Савёлки", unavailable: false, scale: 1.0, parentId: 10 },
  { id: 124, name: "Силино", unavailable: false, scale: 1.0, parentId: 10 },
  {
    id: 125,
    name: "Старое Крюково",
    unavailable: false,
    scale: 1.0,
    parentId: 10,
  },
  {
    id: 126,
    name: "Вороновское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 127,
    name: "Киевский, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 128,
    name: "Клёновское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 129,
    name: "Краснопахорское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 130,
    name: "Михайлово-Ярцевское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 131,
    name: "Новофёдоровское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 132,
    name: "Первомайское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 133,
    name: "Роговское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 134,
    name: "Троицк, городской округ",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 135,
    name: "Щаповское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 11,
  },
  {
    id: 136,
    name: "Внуковское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 137,
    name: "Воскресенское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 138,
    name: "Десёновское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 139,
    name: "Кокошкино, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 140,
    name: "Марушкинское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 141,
    name: "Московский, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 142,
    name: "Мосрентген, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 143,
    name: "Рязановское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 144,
    name: "Сосенское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 145,
    name: "Филимонковское, поселение",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
  {
    id: 146,
    name: "Щербинка, городской округ",
    unavailable: false,
    scale: 1.0,
    parentId: 12,
  },
];

export const scales: Scales = { objectType, wear, series, ao, area };
